apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-repository-deployment
  labels:
    app: simple-repository
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-repository
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
    metadata:
      labels:
        app: simple-repository
    spec:
      containers:
      - name: simple-repository
        # image: IMAGE_TAG
        image: annicet/simple-repository
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
        ports:
          - containerPort: 8080
